### PR TITLE
chore: update sdk dependencies

### PR DESCRIPTION
**Pull request by marianogoldman**

### CODE REVIEW

**Comment by marianogoldman** [comment]
@faustbrian I see you added pnpm to the project. So I guess we shouldn't use npm anymore.
* Do we need to remove `package-lock.json`?
* We'll need to change `c[d|f|i].yml` to use `pnpm` rather than `npm`.

**Comment by faustbrian** [comment]
I only added the pnpm lockfile because npm currently fails to build the project for me but pnpm has no issues. Will remove the lockfile once I sorted it on my end.

**Comment by marianogoldman** [comment]
> I only added the pnpm lockfile because npm currently fails to build the project for me but pnpm ha



> I only added the pnpm lockfile because npm currently fails to build the project for me but pnpm has no issues. Will remove the lockfile once I sorted it on my end.

Ah, ok.
Please wait, and let's update also crypto to 1.1.1 once it's done publishing.

**Comment by faustbrian** [comment]
Just published it. Will need to update it in the SDK.

**Pull request merged**
